name: push_nuget

# on push on master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@master
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
  
    - name: Build
      run: msbuild RCPSharp.sln /t:Build /v:m /m /restore /p:Configuration=Release 
      
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Nuget Pack
      run: nuget pack ./deployment/RCPSharp.nuspec
      
    - name: Nuget Push
      run: nuget push *.nupkg ${{secrets.NUGET_KEY}} -src https://api.nuget.org/v3/index.json -NoSymbols
